aremmell/libsir

sirconfig.h, sirhelpers.h, sirplatform.h, sirtypes.h, tests/tests.h
* Fix macros; closes:
*  #26
*  #28
*  #33
*  #34
* Also remove useless whitespace
=> Fix macros; closes #26, #28, #33, #34

sirinternal.c
* Simplify assignment; closes:
*  #31
=> Simplify assignment; closes #31

sirhelpers.c
* Simplify redundant condition; closes:
*  #20
=> Simplify redundant condition; closes #20

.editorconfig
- Hopefully will avoid trailing whitespace and tabs from sneaking in
=> Add a simple EditorConfig configuration file

sirerrors.c
* Fix typo affecting old glibc builds
=> Fix typo affecting old glibc builds

sirhelpers.c
=> Quiet cppcheck warning; closes #19

sirtextstyle.c
Fixes:
```c
return updated;
return false;
```
=> Remove unreachable code

sirplatform.h
* Add support for IBM XL C/C++ V16.1
=> Add support for IBM XL C/C++ V16.1

example/example.c
* Fix a typo in the example program
=> Fix a typo in the example program

.gitattributes, .gitignore, Makefile
* [Delete logs/* and *.ln during make clean](https://github.com/aremmell/libsir/commit/5c1905655dc2c0b5306210f83577c275a84837a6) 
* [Add Emacs temporary files to .gitignore](https://github.com/aremmell/libsir/commit/2ab70993bc3f4012ccafbe893a032b70628b7dc6) 
* [Don't count documentation towards GitHub language detection](https://github.com/aremmell/libsir/commit/1f5042900f14f2f4060857bc77e072c0fcfe02b5)
=> Minor cleanup

Makefile
* Don't run advpng unnecessarily 
Closes #124
=> Don't use advpng unnecessarily.

README.md, sirfilesystem.c, sirinternal.c, sirplatform.h
=> Add support for SerenityOS

sirerrors.c, sirerrors.h
=> More printf verification

Doxyfile
* Use new TIMESTAMP tag  in Doxyfile
=> Use new TIMESTAMP tag  in Doxyfile

Makefile
* Deparallelize on clean and install make targets
=> Deparallelize on clean and install make targets

sirfilecache.c, sirhelpers.h, sirinternal.c, sirplugins.c, sirtextstyle.c
This code is used a lot, and it's repetitious. Let's stick to the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and not have the same if-statement everywhere (well, it'll still be there, but at least you can't see it).
=> use macros to enter/leave locked sections

sir.h
Please check for spelling, grammar, punctuation, correctness, formatting, uniformity, etc.
I also made changes to the docs for the file API so that they match.
=> Finalize Doxygen docs for external plugin API

example/example.c, sirfilecache.c, sirhelpers.h, sirtypes.h, tests/tests.c
=> A better sirfileid

sirplugins.c
Just leaving notes for future us, so we remember what we need to do if we make a release, but then decide to add to the plugin interface after the fact.
=> Plugin versioning

.coveralls.sh
* This is a bit brittle; won't work in Docker containers or in chroot-style jails, but hopefully OK in VMs and Travis CI.
=> Try to unmount proc for a test.

README.md
* Move all badges to shields.io
* Normalize badge colors
* Add a commits-since release badge
=> Improve badging in README

.gitlab-ci.yml, .gitlab-ci/base/Dockerfile, .gitlab-ci/dmd/Dockerfile, .gitlab-ci/intel/Dockerfile, .gitlab-ci/llvm-mingw/Dockerfile, .gitlab-ci/msvc/Dockerfile, .gitlab-ci/nvhpc/Dockerfile, .gitlab-ci/oracle/Dockerfile, include/sir/platform.h
* Update and rebuild Docker images for CI/CD
* Improve `sir/platform.h` readability
* Add GCC Analyzer CI job
=> Improve `sir/platform.h` readability; Add GCC Analyzer CI job; Update CI images

.lint.sh
Don't enable some unnecessary suppressions
=> Tighten up some Cppcheck rules

.gitlab-ci/base/Dockerfile, .gitlab-ci/embarcadero/Dockerfile, .gitlab-ci/ndk/Dockerfile, .gitlab-ci/oracle/Dockerfile, .gitlab-ci/orangec/Dockerfile, .gitlab-ci/scripts/build.sh
* Allow override of local URLs via Docker build CLI
* Also done for ao64 image in 04394c61c633007204c95febfaf1ffbbf97f78d1 pending in https://github.com/aremmell/libsir/pull/227
=> Allow override of local URLs via Docker build CLI

.gitlab-ci.yml, sirplatform.mk
* Support Windows/Arm (ARMv7) builds using LLVM-MinGW and add to CI
* Support Windows/Arm64 (AArch64) builds using LLVM-MinGW and add to CI
=> Support Windows/Arm (ARMv7) and Windows/Arm64 (AArch64) builds using LLVM-MinGW and add to CI

.lint.sh, include/sir/helpers.h, include/sir/platform.h, src/sir.c, src/sirerrors.c, src/sirfilecache.c, src/sirinternal.c, src/sirplugins.c, src/sirtextstyle.c, tests/tests.c, tests/tests.h
* Use (and pass) Clang's `-Wextra-semi-stmt` check and enable in CI
=> Use (and pass) Clang's ` -Wextra-semi-stmt` check and enable in CI

.gitlab-ci.yml
* Only allow Coverity job on master
=> Only allow Coverity job on master

include/sir/types.h, src/sirhelpers.c, tests/tests.c
- SIRU_
- SIRSL_
- Also pass `0U` to `INIT` in tests to avoid warnings
=> Change more types to uintxx_t instead of enum

include/sir/types.h, tests/tests.c
=> Autoformat

.gitlab-ci.yml, .lint.sh
* Add DUMA as a separate CI test
* Fix skipping DUMA and other non-existent tools on macOS in linter script
=> Fix skipping DUMA and other non-existent tools on macOS in linter script

.gitlab-ci.yml, include/sir/platform.h, msvs/libsir.vcxproj, msvs/plugin_dummy.vcxproj, msvs/plugin_dummy_bad1.vcxproj, msvs/plugin_dummy_bad2.vcxproj, msvs/plugin_dummy_bad3.vcxproj, msvs/plugin_dummy_bad4.vcxproj, msvs/plugin_dummy_bad5.vcxproj, msvs/plugin_dummy_bad6.vcxproj, msvs/plugin_sample.vcxproj, msvs/sirexample.vcxproj, msvs/sirtests.vcxproj
=> Use C11 stdatomic.h when _MSC_VER >= 1933

tests/tests.c
* Use arc4random on more platforms in test harness
=> Use arc4random on more platforms in test harness

src/sirinternal.c
=> Only re-format time stamp string if the numeric time has changed

.gitlab-ci.yml
* Check for `log/*` remnants after running `sirtests`
=> Check for `log/*` remnants after running `sirtests`

include/sir/helpers.h, src/sirfilesystem.c
* Also contains hopeful fix for PVS warning
=> use {0} like everywhere else

.gitlab-ci.yml, .gitlab-ci/uclibc-ng/.config, .gitlab-ci/uclibc-ng/Dockerfile
* Add Linux/x86_64/uClibc-ng toolchain and CI job
=> Add Linux/x86_64/uClibc-ng toolchain and CI job

include/sir/types.h, src/sirinternal.c, tests/tests.c
=> Don't squelch repeating messages that are sent to differing levels

example/example.c, include/sir.hh, include/sir/filecache.h, include/sir/helpers.h, src/sirfilecache.c, src/sirplugins.c, tests/tests++.cc
Going after the low-hanging fruit.
=> Improve test coverage

.gitlab-ci.yml
* Add CFI (Control Flow Integrity) CI jobs
=> Add CFI (Control Flow Integrity) CI jobs

src/sirerrors.c
* Fix compilation with SIR_SELFLOG enabled on AIX
=> Fix compilation with SIR_SELFLOG enabled on AIX

.gitlab-ci.yml, Makefile
* FreeBSD/amd64 (G++, GCC)
* FreeBSD/amd64 (Clang++, Clang)
* FreeBSD/amd64 (DMD64 ImportC, C-only)
* FreeBSD/amd64 (GCC, FreeBSD Python)
=> Add FreeBSD CI jobs

include/sir/condition.h, include/sir/types.h, tests/tests++.cc, tests/tests.c
* Style fixes / normalization
* No functional changes
=> Style fixes / normalization

.coveralls.sh
* Improve test coverage; closes #304
=> Improve test coverage; closes #304

.gitlab-ci.yml
* OpenBSD/amd64 (C++, CC)
* OpenBSD/amd64 (Clang++, Clang)
* OpenBSD/amd64 (CC, OpenBSD Python)
* FreeBSD/amd64 (C++, CC)
=> Add new BSD CI jobs

.gitlab-ci.yml
* NetBSD/amd64 (C++, CC)
* NetBSD/amd64 (G++, GCC)
* NetBSD/amd64 (Clang++, Clang)
* NetBSD/amd64 (CC, NetBSD Python)
=> Add NetBSD CI job

.gitlab-ci.yml
* Request Docker-x64-fast tag for Funcheck job
=> Request Docker-x64-fast tag for Funcheck job

tests/tests.c
* Reduce test iterations (1000 -> 400)
* We are currently using 200 for Emscripten and 100 for DUMA; should keep CI output <512KB for better online browsing.
=> Reduce test iterations (1000 -> 400)

.reuse/dep5, library.json
That's about all there is to it.
=> add PlatformIO library manifest

tests/tests.c
=> Cosmetic alignment

LICENSES/BSD-3-Clause.txt, docs/impl_8h_source.html, docs/platform_8h_source.html, include/sir/impl.h, include/sir/platform.h, src/sirerrors.c
* Add local `strcasestr` implementation, useful for (at least) AIX
=> Add local `strcasestr` implementation

.gitlab-ci/anaconda/Dockerfile, .gitlab-ci/emscripten/Dockerfile, README.md
* Update for latest Emscripten
=> Update for Emscripten

autoformat.sh
=> Exclude build

docs/res/style.css
* Fix spelling in comment: `Souce code` -> `Source code`
=> Fix spelling in comment: `Souce code` -> `Source code`

.coverity.sh
* Update Coverity submission script to work with wget2
=> Update Coverity submission script to work with wget2

msvs/README.md
=> Trim trailing whitespace

.gitlab-ci/kefir/Dockerfile
* Simplify and update syntax for Kefir build in Dockerfile, per suggestions of Kefir author Jevgenij Protopopov
=> Simplify and update syntax for Kefir build in Dockerfile

.github/workflows/scorecard.yml
Use latest versions of each action
=> Upgrade scorecard.yml

.github/workflows/scorecard.yml
If this doesn't work, just going to delete it.
=> Re-install Scorecard

.github/workflows/scorecard.yml
=> Update OSSF Scorecard workflow

.gitlab-ci/dmd/Dockerfile
* Update Linux DMD64 ImportC to v2.109.0
=> Update Linux DMD64 ImportC to v2.109.0

.gitlab-ci.yml, .gitlab-ci/intel/Dockerfile
[CI: Update oneAPI Conda channel; drop Intel Python](https://github.com/aremmell/libsir/commit/0eb5fdccf91eca7ab8451506549fdf606643cbf4)
=> CI: Update oneAPI Conda channel; drop Intel Python

.editorconfig
* Update `.editorconfig` for vendored files
=> Update `.editorconfig` for vendored files
