sirerrors.c

It's always true if it takes the path without XSI_STRERROR_R and XSI_STRERROR_R_ERRNO, and without STRERROR_S, it's simply explicitly set and then checked, not worth refactoring extensively just to avoid the warning.
Closes #22

Add exclusion to fix issue #22

---

sirfilesystem.c
sirinternal.c
sirplatform.h

* Tested on OpenIndiana 2023.05 with GCC 7.5.0, GCC 10.4.0, GCC 11.3.0, and Clang 15.0.7.
* Tested on Solaris 11.4 SRU 42 with GCC 11.2.0 and Clang 11.0.0.

Add support for Solaris and illumos

---

sirfilesystem.c
sirinternal.c
sirplatform.h

* Add support for DragonFly BSD.
* Tested on DragonFly BSD 6.4.0-RELEASE and 6.5-DEVELOPMENT using GCC 8.3.0, GCC 12.2.0, GCC 13.0.0, Clang 14.0.6, Clang 13.0.1, Clang 12.0.1, Clang 11.0.1, and Clang 10.0.1.
[]()
* Add support for NetBSD.
* Tested on NetBSD 9.3-STABLE (ARM64 and AMD64) with Clang 15.0.7, GCC 7.5.0, GCC 12.2.0, and GCC 13.1.0.
---
* The DragonFly BSD support includes a workaround for Clang missing `<stdatomic.h>`.  This affects all Clang packages on DragonFly BSD.  If a future Clang package corrects this issue, the Clang version number may be checked to disable the workaround.

Add support for DragonFly BSD and NetBSD

---

sirfilesystem.c
sirhelpers.c
sirhelpers.h
sirinternal.c
sirplatform.h
sirtextstyle.c
tests/tests.c
tests/tests.h

Will you look this over, and make sure I didn't botch anything? The flawfinder stuff is pretty straightforward:
- use strnlen instead of strlen
- use strlcpy/strlcat when available instead of strncpy/strncat
I moved a few things around to better fit the format that was already in place (i.e. where platform-specific includes are placed, etc.), and broke some long lines.

Flawfinder

---

sirhelpers.c

* Use `strlcpy` and `strlcat` on Solaris and illumos.

Use `strlcpy` and `strlcat` on Solaris and illumos.

---

Makefile
sirconfig.h
sirfilesystem.c
sirinternal.c
sirplatform.h
tests/tests.c

* Tested with [Oracle Developer Studio](https://www.oracle.com/application-development/technologies/developerstudio.html) C/C++ 12.6 on Linux and Solaris.
[]()
[]()
* Tested with [MinGW-w64](https://www.mingw-w64.org/) on Fedora, Ubuntu, and Cygwin, targeting:
* 64-bit UCRT: `make CC=x86_64-mingw32ucrt-gcc`
* 64-bit MSVCRT: `make SIR_MSVCRT_MINGW=1 CC=x86_64-mingw32-gcc`
* 32-bit MSVCRT: `make SIR_MSVCRT_MINGW=1 CC=i686-w64-mingw32-gcc`

Add support for Oracle Developer Studio C and MinGW‑w64.

---

sirhelpers.c
sirtextstyle.c

@aremmell While it still bothers me a bit still that both analyzers flag this, if you want, we can dismiss with these exclusions.

Suppress Clang Analyzer and Cppcheck warnings

---

tests/tests.c

ICC doesn't support OS_ACTIVITY_OBJECT_API due to <10.12 target.  (No great loss, as Intel C++ Compiler Classic is deprecated and will be EOL sometime "in the second half of 2023").

Don't test os_log activity feature if built with Intel C++ Compiler Classic for macOS

---

README.md

* Use `≳` (equal or equiv. to) in places where we known it's a minimum and greater is OK

Use `≳` (equal or equiv. to) in places where we known it's a minimum and greater is OK

---

.gitignore

*  Add all *.d to `.gitignore`
Chibcc and old XL C seems to (incorrectly) drop them into the current working directory.

Add all *.d to `.gitignore`

---

.gitignore
Makefile
sirplatform.mk

* Ensure Makefile has a full dependency graph to avoid unnecessary remakes
* Move platform-specifics toolchain detection stuff into `sirplatform.mk`
* Add flags for Intel C++ Compiler Classic, Chibicc, and NVIDIA HPC SDK C
* Fix installing with `DESTDIR` when using a custom `PREFIX`
* Shrink documentation PNG files using *Advpng*, if available
Closes #87

GNU Makefile improvements

---

sirinternal.c

* Add explicit cast; appease Oracle Lint (assignment of double to long may cause implicit narrowing conversion or loss of precision)
Closes #114

Add explicit cast; appease Oracle Lint (assignment of double to long may cause implicit narrowing conversion or loss of precision)

---

sirerrors.c

* Appease Oracle Lint by eliminating possible dangling/empty else condition

Eliminate possible dangling/empty else condition

---

Makefile

* Properly create `file.exists` (without explicitly running `make tests`)

Properly create `file.exists` (without explicitly running `make tests`)

---

.gitignore
msvs/libsir.vcxproj
msvs/libsir.vcxproj.filters
tests/tests.c
tests/tests.h

- Using --leave-logs causes log files to not be deleted after the test suite runs
- Logs are now sent to `./logs/` instead of the working directory
- We need to delete `./logs/*` on clean, and if the `logs` dir isn't present on make tests, we need to mkdir it

Leave logs

---

.vscode/launch.json
sirhelpers.c
tests/tests.c

Tests relying on `enumfiles` didn't successfully delete their logs because that function only passed back the filename to the callback. Now prefixed with `./logs/`

Fix log deletion

---

Makefile

* Allows setting to `0` and still working as expected.

Small style fix; `ifndef` -> `ifneq` for consistency

---

sirplatform.mk

* Regression caused during reorganization of the tree; only affects the legacy compiler

Fix for building with legacy IBM XL C/C++ for AIX V16

---

tests/tests.h

* The elapsed time is passed to this function, which can be zero because clock_gettime is used to determine the time elapsed. It's possible for clock_gettime to fail, and if that happens it shouldn't cause the test harness to crash.

Don't crash if `upper_bound` is `0`

---

Makefile
sirplatform.mk
tests/tests.c

* The Solaris and illumos options are documented [here](https://docs.oracle.com/cd/E88353_01/html/E37843/mtmalloc-3malloc.html#REFMAN3Amtmalloc-3malloc).
* The OpenBSD options are documented [here](https://man.openbsd.org/malloc).
* `EXTRA_FLAGS` used since the order matters if building statically and the malloc library should always be last.

Enable platform-specific (OpenBSD, Solaris, illumos) malloc options in the test suite.

---

src/sirinternal.c

* Linux with glibc 2.30 and later has `gettid()`; use it when available

Linux with glibc 2.30 and later has `gettid()`; use it when available

---

.coveralls.sh
.gitlab-ci.yml
.gitlab-ci/base/Dockerfile
include/sir/helpers.h
include/sir/platform.h
src/sirhelpers.c
tests/tests.c

* Avoid undefined behavior and integer overflow
* Add new CI jobs ...
* Clang Memory Sanitizer
* Clang Undefined Behavior Sanitizer (32-bit)
* Clang Undefined Behavior Sanitizer (64-bit)
* Clang Address Sanitizer (32-bit)
* Clang Address Sanitizer (64-bit)
* MSVC i686 (32-bit)

Avoid undefined behavior and integer overflow

---

.lint.sh
src/sirinternal.c
src/sirtextstyle.c

* Use (and pass) Clang's `-Wswitch-enum` check and enable in CI

Use (and pass) Clang's `-Wswitch-enum` check and enable in CI

---

.lint.sh
plugins/dummy/plugin_dummy.c
plugins/sample/plugin_sample.c
src/sirtextstyle.c
tests/tests.c

* Use (and pass) Clang's `-Wmissing-variable-declarations` check and enable in CI

Use (and pass) Clang's `-Wmissing-variable-declarations` check and enable in CI

---

include/sir/platform.h
src/sirerrors.c
src/sirinternal.c

* Use system `strlcat` and `strlcpy` on Linux/glibc >= 2.38
* Use system `strlcat` and `strlcpy` on Haiku
* Improve glibc version checking macros

Use system strlcat & strlcpy on Linux/glibc >= 2.38 and Haiku

---

include/sir/platform.h
tests/tests.c

- Detection was broken at the preprocessor level. Fixed it so that if the target system is macOS and the compiler is Clang, define.
- Fixed two implicit conversion warnings that we didn't catch because this preprocessor macro was never enabled.

Fix SIR_OS_LOG_ENABLED

---

include/sir/config.h
include/sir/platform.h
src/sirhelpers.c
src/sirinternal.c

* Use `localtime_r` for improved performance

Use localtime_r for improved performance

---

include/sir/helpers.h

I always write `n` in my for-loops. cppcheck caught this one.

Don't use variable name 'n' in macro

---

include/sir/config.h
include/sir/types.h
src/sirfilecache.c

Should improve write perf since fstat() is such a heavy call. There's no need to check it on every write, since relative to the roll size, one write is barely a dent.

don't fstat log files on every write, only every n

---

.gitlab-ci.yml

* Require AVX tag on NVIDIA CI job

Require AVX tag on NVIDIA CI job

---

src/sirinternal.c
tests/tests.c

* Fix `_sir_getthreadname` and `_sir_setthreadname`
* Don't use `arc4random_uniform`

Some minor fixes for ucLibc-ng toolchains

---

include/sir/helpers.h
src/sirhelpers.c
tests/tests.c

* As-is, some errors will always appear to be originating from sirhelpers.c, which is not useful. Changing these to macros will allow us to capture __func__, __file__, __LINE__, and store that in the error information.
* Also fixed a minor bug in plugin loader test

macroize _sir_valid* functions in order to capture source info

---

include/sir/internal.h
src/sirinternal.c

This will fix the case of cleanup/init in a loop, in which less than 1s elapses (time stamp doesn't get generated)

reset tls data on cleanup; only copy tid/name if set

---

include/sir/helpers.h

This should give us a tiny perf gain, and eliminates a useless code path.

_sir_validstrnofail does not need to call __sir_validstr

---

include/sir/filecache.h
include/sir/filesystem.h
include/sir/helpers.h
include/sir/types.h
src/sirfilecache.c
src/sirfilesystem.c
src/sirhelpers.c

Performance gains not present (or net negative), and entropy in source is unbalancing. Saving some changes that were beneficial.

Revert PR #268.

---

.gitignore
msvs/sirexample.vcxproj.user
msvs/sirtests.vcxproj.user

* These files are required to properly set the working directory when launching from within Visual Studio (test rig will fail otherwise)

add .user files for sirtests and sirexample, ignore the rest

---

include/sir.h
include/sir/internal.h
src/sir.c
src/sirinternal.c
tests/tests.c
tests/tests.h

* Determines whether or not libsir is in the initialized state without setting an error if it is not.

add `sir_isinitialized` convenience function

---

README.md
bindings/python/sir.i
include/sir.h
include/sir.hh
include/sir/errors.h
include/sir/types.h
src/sir.c
src/sirerrors.c
tests/tests++.cc
tests/tests++.hh
tests/tests.c

In the event that a caller is not satisfied with (or is otherwise precluded from using) the default error message formatting, we're adding `sir_geterrorinfo` (and associated C++ types/methods).
This allows for the retrieval of all of the information about the error, piecemeal:
* function name
* file name
* line number
* libsir error code
* libsir error message
* OS/libc error code
* OS/libc error message
> I also got a bit sidetracked, forgot I was on this branch for one purpose and started editing doxgyen C++ comments... 😬 
Closes #295.

Add sir_geterrorinfo to obtain extended information about an error

---

.coverity.sh

* Use `SIR_NO_FMT_FORMAT=1` and `SIR_NO_BOOST_FORMAT=1` for Coverity submission build.

Use `SIR_NO_FMT_FORMAT=1` and `SIR_NO_BOOST_FORMAT=1` for Coverity submission build.

---

.coverity.sh
.gitlab-ci.yml
.lint.sh

* Exempt scanning some third-party dependencies with Coverity
* Appease ShellCheck on `.lint.sh`
* Use 15 minute timeout for Semgrep jobs

Minor CI tweaks

---

src/sirhelpers.c

* Don't require output param
* Don't use memcpy

refactor _sir_getchar

---

src/sirfilecache.c
tests/tests.c

* File names beginning with ./ would fail to be rolled/archived because the file name splitting routine used left of `.` as the name part, and right as extension; in this case, the name part is empty, and so the routine returns false

Fix: file name splitting with `./` prefix

---

src/sirfilecache.c

* Don't check idx, check sfc->count, which should teach it that the for statement can't run if idx is out of bounds

try to appease coverity by rearranging boundary checks

---

LICENSES/X11.txt
build-aux/install-sh

* Annotate `build-aux/install-sh` to pass ShellCheck
* No functional changes to legacy-proof code, annotation only

Annotate `build-aux/install-sh` to pass ShellCheck

---

.gitlab-ci.yml

* Explicitly enable two-phase name lookup in MSVC in CI
* Mostly for example usage since it's now default in 17.7+
* https://devblogs.microsoft.com/cppblog/two-phase-name-lookup-support-comes-to-msvc/

Explicitly enable C++ two-phase name lookup in MSVC

---

.lint.sh
autoformat.sh
include/sir/threadpool.h
src/sirfilecache.c
src/sirfilesystem.c
src/sirhelpers.c
src/sirinternal.c
src/sirplugins.c
tests/tests.c

- variable `foo` can be declared as pointer to const
- local variable `foo` shadows outer function
- the scope of the variable `foo` can be reduced
- condition `foo` is always true/false
- function argument 2 names different
- variable `foo` is assigned a value that is never used
- variable `foo` is reassigned a value before the old one has been used

Tweaks based on cppcheck linter warnings

---

sirplatform.mk

* Always build with `-D_THREAD_SAFE` on OS/400 and AIX
* This allows building working Python bindings without special flags

Always build with `-D_THREAD_SAFE` on OS/400 and AIX

---

.gitlab-ci.yml

* Comment out musl-gcc test due to upstream bug RHBZ#2263904
* https://bugzilla.redhat.com/show_bug.cgi?id=2263904

Comment out musl-gcc test due to upstream bug RHBZ#2263904

---

.gitlab-ci.yml

* Add AVX tag to PVS-Studio job
* Older Core 2 runner is failing with latest beta otherwise

Add AVX tag to PVS-Studio job

---

.gitignore
tests/tests.c

* The NULL pointer test now additionally raises a V575 (*null pointer is passed*) on top of the V618 (*dangerous use of function*), in the `sirtest_failnulls` function in `tests/tests.c`.
Suppressing this warning, because the test does this intentionally.
* Also, add `compile_commands.events.json` to the `.gitignore` file.

Appease latest PVS-Studio 7.29.80616.6568

---

Makefile

Allows building without warnings on current Android/Termux

Workaround for `getconf` that doesn't support PATH
